# Generated by Django 5.0.3 on 2024-06-27 18:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectName', models.CharField(max_length=50)),
                ('subjectImage', models.ImageField(upload_to='subjectimages')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseImage', models.ImageField(help_text='image size should be below 10mb', upload_to='subjectimages')),
                ('courseName', models.CharField(max_length=100)),
                ('coursePrice', models.PositiveIntegerField(help_text='Enter Price in dollars')),
                ('courseDuration', models.DurationField(default=datetime.timedelta(seconds=22800))),
                ('courseSubject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='home.subjects')),
            ],
        ),
    ]
