# Generated by Django 5.0.6 on 2024-07-02 07:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjects',
            options={'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.RenameField(
            model_name='subjects',
            old_name='subjectName',
            new_name='subjectname',
        ),
        migrations.AlterField(
            model_name='course',
            name='courseDuration',
            field=models.DurationField(default=datetime.timedelta(seconds=22800), verbose_name=' Course Duration'),
        ),
        migrations.AlterField(
            model_name='course',
            name='courseImage',
            field=models.ImageField(help_text='image size should be below 10mb', upload_to='subjectimages', verbose_name='Course Image'),
        ),
        migrations.AlterField(
            model_name='course',
            name='courseName',
            field=models.CharField(max_length=100, verbose_name='Course Name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='coursePrice',
            field=models.PositiveIntegerField(help_text='Enter Price in dollars', verbose_name='Course Price'),
        ),
        migrations.AlterField(
            model_name='course',
            name='courseSubject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='home.subjects', verbose_name='Course Subject'),
        ),
    ]
