# Generated by Django 5.0.3 on 2024-07-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_rename_tag_project_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featuredd_image',
            field=models.ImageField(blank=True, default='images/profiles/default.jpeg', null=True, upload_to='images/profiles/'),
        ),
    ]
