# Generated by Django 5.0.3 on 2024-07-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_featuredd_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='featuredd_image',
        ),
        migrations.AddField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
