# Generated by Django 5.0.3 on 2024-07-02 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseTitle', models.CharField(max_length=100, verbose_name='Course Name')),
                ('courseImage', models.ImageField(help_text='image size should be below 10mb', upload_to='subjectimages', verbose_name='Course Image')),
                ('courseName', models.CharField(max_length=100, verbose_name='Course Name')),
                ('coursePrice', models.PositiveIntegerField(help_text='Enter Price in dollars', verbose_name='Course Price')),
                ('courseDuration', models.DurationField(default=datetime.timedelta(seconds=22800), verbose_name=' Course Duration')),
            ],
        ),
    ]
