# Generated by Django 5.0.3 on 2024-07-02 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolAdmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='courseTitle',
        ),
        migrations.AlterField(
            model_name='course',
            name='courseDuration',
            field=models.DurationField(default=datetime.timedelta(seconds=22800), verbose_name='Course Duration'),
        ),
    ]
