# Generated by Django 5.0.3 on 2024-06-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('user_story', models.TextField(blank=True, null=True)),
                ('profilePic', models.ImageField(upload_to='profile')),
                ('DateofBirth', models.DateField()),
                ('DateofRegistration', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=50)),
                ('useResume', models.FileField(upload_to='cvs')),
                ('salary', models.PositiveIntegerField()),
                ('height', models.FloatField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Any other', 'Any other')], max_length=30)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
    ]
